import React from 'react';
import { Link } from 'react-router-dom';
import BrandPageShell from './components/BrandPageShell';
import './Brand.css';

const SecurityPage: React.FC = () => {
  return (
    <BrandPageShell contentClassName="brand-security-layout">

      {/* ── Hero ── */}
      <header className="brand-security-hero">
        <p className="eyebrow">Trust & Security</p>
        <h1>How AetherGIS <span className="brand-accent">protects</span> your sessions</h1>
        <p className="brand-security-hero-sub">
          Platform security controls across authentication, compute isolation, API protection,
          and data handling — designed for responsible AI-augmented research workflows.
        </p>
      </header>

      {/* ── Top KPIs ── */}
      <div className="brand-security-kpis">
        {[
          { stat: 'OAuth 2.0', label: 'Authentication standard' },
          { stat: 'KOTH Lock', label: 'Single-session GPU isolation' },
          { stat: 'HTTPS', label: 'End-to-end encryption' },
          { stat: 'Zero PII', label: 'No personal data stored' },
        ].map(({ stat, label }) => (
          <div key={stat} className="brand-security-kpi">
            <span className="brand-security-kpi-stat">{stat}</span>
            <span className="brand-security-kpi-label">{label}</span>
          </div>
        ))}
      </div>

      {/* ── Control cards ── */}
      <section className="brand-security-section">
        <p className="eyebrow" style={{ marginBottom: 16 }}>Security Controls</p>
        <div className="brand-security-grid">

          <article className="brand-security-card">
            <div className="brand-security-card-icon brand-security-icon-blue">⊙</div>
            <h3>Authentication</h3>
            <p>
              Production deployments use Google OAuth 2.0 via the
              <code>/api/v1/auth/login</code> flow. Session tokens are short-lived JWTs
              scoped to a single dashboard session. Local development mode bypasses auth
              and is never exposed in production builds.
            </p>
          </article>

          <article className="brand-security-card">
            <div className="brand-security-card-icon brand-security-icon-cyan">⬡</div>
            <h3>GPU Session Lock (KOTH)</h3>
            <p>
              The King-of-the-Hill queue ensures only one pipeline can hold the GPU at any
              time. New submissions receive an HTTP 409 with their queue position. This
              prevents resource contention and ensures reproducible compute allocation.
            </p>
          </article>

          <article className="brand-security-card">
            <div className="brand-security-card-icon brand-security-icon-green">◈</div>
            <h3>API Rate Limiting</h3>
            <p>
              Pipeline submission endpoints enforce per-IP and per-session rate limits.
              Abuse-pattern detection is applied at the reverse proxy level before requests
              reach the FastAPI backend, reducing the attack surface.
            </p>
          </article>

          <article className="brand-security-card">
            <div className="brand-security-card-icon brand-security-icon-purple">⊕</div>
            <h3>Data Handling</h3>
            <p>
              AetherGIS does not store personally identifiable information. Pipeline inputs
              (AOI, time range, layer selection) are ephemeral per-job parameters. Generated
              outputs are stored with job-scoped UUIDs and are not publicly indexable.
            </p>
          </article>

          <article className="brand-security-card">
            <div className="brand-security-card-icon brand-security-icon-orange">◎</div>
            <h3>Transport Security</h3>
            <p>
              All production endpoints are served over HTTPS with HSTS headers. WebSocket
              connections for real-time job status use WSS. Certificates are managed via
              the deployment infrastructure and rotated automatically.
            </p>
          </article>

          <article className="brand-security-card">
            <div className="brand-security-card-icon brand-security-icon-blue">⊞</div>
            <h3>AI Output Disclaimer</h3>
            <p>
              Synthetic frames generated by RIFE/FILM are clearly marked in the UI and API
              responses. Confidence scores are provided for every frame. This prevents
              misinterpretation of AI-generated content as observed satellite data.
            </p>
          </article>

        </div>
      </section>

      {/* ── Responsible AI ── */}
      <section className="brand-security-responsible">
        <div className="brand-security-responsible-content">
          <p className="eyebrow">Responsible AI</p>
          <h2>AI transparency by design</h2>
          <p>
            Every AI-generated frame in AetherGIS carries an explicit <strong>is_synthetic</strong> flag
            and a scalar confidence score. The platform never presents interpolated content as ground truth.
            Frames below the configured confidence threshold are excluded from default playback and visually
            distinguished in the timeline.
          </p>
          <p>
            This design ensures that domain experts always have the information they need to make
            informed judgements about whether a frame is suitable for their specific use case.
          </p>
        </div>
        <div className="brand-security-responsible-aside">
          <div className="brand-security-disclaimer-card">
            <h4>Platform Disclaimer</h4>
            <p>
              AI-interpolated outputs are synthetic approximations intended for qualitative
              analysis only. They are not suitable for scientific measurement, operational
              forecasting, or any decision-making without domain expert review.
            </p>
            <Link to="/disclaimer" className="brand-security-disclaimer-link">
              Read full disclaimer →
            </Link>
          </div>
        </div>
      </section>

      {/* ── Contact security ── */}
      <section className="brand-security-contact">
        <h2>Security Issues?</h2>
        <p>
          If you discover a vulnerability in the platform, please report it responsibly.
          We review all security disclosures and respond within 48 hours.
        </p>
        <a href="mailto:security@aethergis.ai" className="brand-btn brand-btn-primary">
          Contact Security Team
        </a>
      </section>

    </BrandPageShell>
  );
};

export default SecurityPage;
